### ISSUE TITLE
run github version?

### ISSUE THREAD

**Issue by jots** [rhysd/Tilectron#1]
This looks like a fascinating project!
Do you have any hints on how to run it from a git clone?
I:  git cloned, then npm install .
and tried:

```
$ bin/cli.js 
Error opening app
The app provided is not a valid electron app
```

**Comment by rhysd** [comment]
Please build with `rake` as below.

``` sh
$ rake build
$ ./bin/cli.js
```

It also needs `tsd` command.

**Comment by jots** [comment]
Thank you, that worked!
nothing happens when I enter text into the "URL or words..." box and hit enter, but I'll dig into that.

**Comment by rhysd** [comment]
You can use DevTools with the same keyboard shortcut `Cmd+option+i` (ctrl+shift+i for Windows and Linux).
If you want to query something, please feel free to make issues.
