### ISSUE TITLE
error when entering into omni-input

### ISSUE THREAD

**Issue by jots** [rhysd/Tilectron#2]
when entering text into the omni-input and hit enter, this error is shown in the console:

`Uncaught TypeError: Cannot read property 'addEventListener' of undefined`
page-state.js line 66:

```
        this.webvew.addEventListener(
            'close',
            () => dispatch(closeTile(this.tile_id))
        );
    }
```

if I try to execute statements in the console, the process dies.

I'm on ubuntu 14.04

**Comment by rhysd** [comment]
@jots 

I could reproduced and fixed.  Thanks!

**Comment by jots** [comment]
that worked. thanks!  I can't believe I didn't see that typo.

**Comment by rhysd** [comment]
:flushed:
